package com.ahogek.cttserver.fixtures;

import com.ahogek.cttserver.audit.entity.AuditLog;
import com.ahogek.cttserver.user.entity.User;

import org.springframework.boot.jpa.test.autoconfigure.TestEntityManager;

import java.util.List;
import java.util.UUID;
import java.util.stream.Stream;

/**
 * Unified persistence utilities for Repository and Integration tests.
 *
 * <p><b>Usage scope:</b> Only use in tests that need real database operations (@BaseRepositoryTest
 * / @BaseIntegrationTest). Service and Controller Slice tests should use fixture.build() directly
 * without persistence.
 *
 * <p><b>Example usage:</b>
 *
 * <pre>{@code
 * @BaseRepositoryTest
 * class UserRepositoryTest {
 *     @Autowired TestEntityManager em;
 *
 *     @Test
 *     void findByEmail_returnsUser() {
 *         var user = PersistedFixtures.user(em, UserFixtures.regularUser());
 *
 *         assertThat(user.getId()).isNotNull();  // ID generated by DB
 *         assertThat(user.getCreatedAt()).isNotNull();  // Timestamp filled
 *     }
 * }
 *
 * @BaseIntegrationTest
 * class AuditIntegrationTest {
 *     @Autowired TestEntityManager em;
 *
 *     @Test
 *     void auditLog_isPersisted() {
 *         var user = PersistedFixtures.regularUser(em);
 *         var audit = PersistedFixtures.auditLog(em, AuditFixtures.loginSuccess(user.getId()));
 *
 *         assertThat(audit.getId()).isNotNull();
 *     }
 * }
 * }</pre>
 *
 * <p><b>Why TestEntityManager:</b> Using {@code em.persistFlushFind(entity)} ensures:
 *
 * <ul>
 *   <li>Entity is immediately flushed to database
 *   <li>Generated IDs are available
 *   <li>JPA lifecycle callbacks (@CreationTimestamp, @PrePersist) are executed
 *   <li>Entity is detached after flush, simulating real persistence behavior
 * </ul>
 *
 * @author AhogeK
 * @since 2026-03-18
 */
public final class PersistedFixtures {

    private PersistedFixtures() {}

    // ==========================================
    // User Persistence
    // ==========================================

    /**
     * Persists a user from a builder and returns the managed entity.
     *
     * <p>The returned entity has all JPA-generated fields populated (id, createdAt, updatedAt).
     *
     * @param em TestEntityManager for persistence
     * @param builder user builder (e.g., UserFixtures.regularUser())
     * @return managed User entity with generated ID
     */
    public static User user(TestEntityManager em, UserFixtures.Builder builder) {
        return em.persistFlushFind(builder.build());
    }

    /** Persists a regular user with default settings. */
    public static User regularUser(TestEntityManager em) {
        return user(em, UserFixtures.regularUser());
    }

    /** Persists an admin user with default settings. */
    public static User admin(TestEntityManager em) {
        return user(em, UserFixtures.admin());
    }

    /** Persists a locked user (5 failed login attempts). */
    public static User lockedUser(TestEntityManager em) {
        return user(em, UserFixtures.lockedUser());
    }

    /** Persists a pending user (unverified email). */
    public static User pendingUser(TestEntityManager em) {
        return user(em, UserFixtures.pendingUser());
    }

    /** Persists a suspended user. */
    public static User suspendedUser(TestEntityManager em) {
        return user(em, UserFixtures.suspendedUser());
    }

    // ==========================================
    // Audit Log Persistence
    // ==========================================

    /**
     * Persists an audit log from a builder and returns the managed entity.
     *
     * <p>The returned entity has all JPA-generated fields populated (id, createdAt).
     *
     * @param em TestEntityManager for persistence
     * @param builder audit log builder (e.g., AuditFixtures.loginSuccess(userId))
     * @return managed AuditLog entity with generated ID
     */
    public static AuditLog auditLog(TestEntityManager em, AuditFixtures.Builder builder) {
        return em.persistFlushFind(builder.build());
    }

    /** Persists a login success audit event. */
    public static AuditLog loginSuccess(TestEntityManager em, UUID userId) {
        return auditLog(em, AuditFixtures.loginSuccess(userId));
    }

    /** Persists a login failed audit event. */
    public static AuditLog loginFailed(TestEntityManager em, UUID userId, String reason) {
        return auditLog(em, AuditFixtures.loginFailed(userId, reason));
    }

    /** Persists an account locked audit event. */
    public static AuditLog accountLocked(TestEntityManager em, UUID userId, int attemptCount) {
        return auditLog(em, AuditFixtures.accountLocked(userId, attemptCount));
    }

    // ==========================================
    // Utility Methods for Test Setup
    // ==========================================

    /**
     * Creates and persists multiple users in one transaction.
     *
     * <p>Useful for tests needing multiple users (pagination, search, etc.).
     *
     * @param em TestEntityManager for persistence
     * @param count number of users to create
     * @return list of managed User entities
     */
    public static List<User> createUsers(TestEntityManager em, int count) {
        return Stream.generate(() -> regularUser(em)).limit(count).toList();
    }
}
